[versions]
agp = "8.13.1"
firebaseBom = "34.6.0"
horologist = "0.7.15"
kotlin = "2.2.21"
kotlinx = "1.9.0"
ksp = "2.2.21-2.0.4"

coreKtx = "1.17.0"

hilt = "2.57.2"
hiltCommon = "1.3.0"
googleServices = "4.4.4"

junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.0"
composeBom = "2025.11.01"
material3 = "1.5.0-alpha10"
nav3ViewModel = "2.10.0"
nav3adaptive = "1.0.0-alpha03"
navigation3 = "1.0.0"
mockup = "1.2.4"

protoLayoutVersion = "1.3.0"
room = "2.8.4"
shapes = "1.1.0"
playServicesWearable = "19.0.0"
tiles = "1.5.0"
wearComposeMaterial3 = "1.6.0-alpha06"
composeFoundation = "1.5.5"
wearToolingPreview = "1.0.0"
coreSplashscreen = "1.2.0"
annotationJvm = "1.9.1"
uiTooling = "1.9.5"
appcompat = "1.7.1"
material = "1.13.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-shapes = { module = "androidx.graphics:graphics-shapes", version.ref = "shapes" }
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
wear-compose-material3 = { group = "androidx.wear.compose", name = "compose-material3", version.ref = "wearComposeMaterial3" }
androidx-compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "composeFoundation" }
androidx-wear-tooling-preview = { group = "androidx.wear", name = "wear-tooling-preview", version.ref = "wearToolingPreview" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }
androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "uiTooling" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }


firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }

hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltCommon" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCommon" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-common = { module = "androidx.hilt:hilt-common", version.ref = "hiltCommon" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
dagger-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

horologist-compose = { module = "com.google.android.horologist:horologist-compose-tools", version.ref = "horologist" }
horologist-tiles = { module = "com.google.android.horologist:horologist-tiles", version.ref = "horologist" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mockup-processor = { module = "com.github.miroslavhybler:ksp-mockup-processor", version.ref = "mockup" }
mockup-annotations = { module = "com.github.miroslavhybler:ksp-mockup-annotations", version.ref = "mockup" }

navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui-android", version.ref = "navigation3" }
navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3" }
navigation3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "nav3adaptive" }
navigation3-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "nav3ViewModel" }

serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx" }

wear-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "composeFoundation" }
wear-protolayout-material3 = { module = "androidx.wear.protolayout:protolayout-material3", version.ref = "protoLayoutVersion" }
wear-protolayout-expression = { module = "androidx.wear.protolayout:protolayout-expression", version.ref = "protoLayoutVersion" }
wear-protolayout = { module = "androidx.wear.protolayout:protolayout", version.ref = "protoLayoutVersion" }
wear-tiles-tooling-preview = { module = "androidx.wear.tiles:tiles-tooling-preview", version.ref = "tiles" }
wear-tiles-tooling = { module = "androidx.wear.tiles:tiles-tooling", version.ref = "tiles" }
wear-tiles = { module = "androidx.wear.tiles:tiles", version.ref = "tiles" }

room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }

hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }